packages:
  - "apps/*"
  - "packages/*"

catalog:
  "react": ^18
  "react-dom": ^18
  "typescript": ^5
  "@tanstack/react-query": ^5.84.2
  "vite": ^6.0.11
  "@vanilla-extract/css": ^1.17.4
  "radix-ui": "^1.4.3"
