/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithAuthRouteImport } from './routes/_withAuth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerificationIndexRouteImport } from './routes/verification/index'
import { Route as SigninIndexRouteImport } from './routes/signin/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as WithAuthProfileIndexRouteImport } from './routes/_withAuth/profile/index'
import { Route as WithAuthMainIndexRouteImport } from './routes/_withAuth/main/index'

const WithAuthRoute = WithAuthRouteImport.update({
  id: '/_withAuth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationIndexRoute = VerificationIndexRouteImport.update({
  id: '/verification/',
  path: '/verification/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninIndexRoute = SigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const WithAuthProfileIndexRoute = WithAuthProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => WithAuthRoute,
} as any)
const WithAuthMainIndexRoute = WithAuthMainIndexRouteImport.update({
  id: '/main/',
  path: '/main/',
  getParentRoute: () => WithAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/signin': typeof SigninIndexRoute
  '/verification': typeof VerificationIndexRoute
  '/main': typeof WithAuthMainIndexRoute
  '/profile': typeof WithAuthProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/signin': typeof SigninIndexRoute
  '/verification': typeof VerificationIndexRoute
  '/main': typeof WithAuthMainIndexRoute
  '/profile': typeof WithAuthProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_withAuth': typeof WithAuthRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/verification/': typeof VerificationIndexRoute
  '/_withAuth/main/': typeof WithAuthMainIndexRoute
  '/_withAuth/profile/': typeof WithAuthProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signin' | '/verification' | '/main' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signin' | '/verification' | '/main' | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_withAuth'
    | '/login/'
    | '/signin/'
    | '/verification/'
    | '/_withAuth/main/'
    | '/_withAuth/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WithAuthRoute: typeof WithAuthRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  SigninIndexRoute: typeof SigninIndexRoute
  VerificationIndexRoute: typeof VerificationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_withAuth': {
      id: '/_withAuth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification/': {
      id: '/verification/'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_withAuth/profile/': {
      id: '/_withAuth/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof WithAuthProfileIndexRouteImport
      parentRoute: typeof WithAuthRoute
    }
    '/_withAuth/main/': {
      id: '/_withAuth/main/'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof WithAuthMainIndexRouteImport
      parentRoute: typeof WithAuthRoute
    }
  }
}

interface WithAuthRouteChildren {
  WithAuthMainIndexRoute: typeof WithAuthMainIndexRoute
  WithAuthProfileIndexRoute: typeof WithAuthProfileIndexRoute
}

const WithAuthRouteChildren: WithAuthRouteChildren = {
  WithAuthMainIndexRoute: WithAuthMainIndexRoute,
  WithAuthProfileIndexRoute: WithAuthProfileIndexRoute,
}

const WithAuthRouteWithChildren = WithAuthRoute._addFileChildren(
  WithAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WithAuthRoute: WithAuthRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  SigninIndexRoute: SigninIndexRoute,
  VerificationIndexRoute: VerificationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
