import type { CSSProperties } from "react";

export const errorTextStyle: CSSProperties = {
  color: "#ef4444",
  fontSize: "12px",
};

export const DEPARTMENT = [
  "건축공학전공",
  "건축학전공",
  "경영대학",
  "경영학부",
  "경제학부",
  "공간정보공학과",
  "공과대학",
  "교양교육부",
  "교양물리",
  "교양생물",
  "교양수학",
  "교양영어",
  "교양체육",
  "교양컴퓨터",
  "교양화학",
  "교직부",
  "교통공학과",
  "교통공학과(SMTE)",
  "국사학과",
  "국어국문학과",
  "국제관계학과",
  "국제교육원",
  "국제교류과",
  "자유전공학부",
  "국제도시개발학전공",
  "도시부동산기획경영학전공",
  "미디어콘텐츠학",
  "기계정보공학과",
  "도시공학과",
  "도시과학대학",
  "도시문화콘텐츠학",
  "도시사회학과",
  "도시행정학과",
  "동아시아문화학전공",
  "물리학과",
  "법규범제도학",
  "빅데이터분석학전공",
  "사회복지학과",
  "산업디자인전공",
  "생명과학과",
  "세무학과",
  "소방방재학과",
  "수학과",
  "스포츠과학과",
  "시각디자인전공",
  "신소재공학과",
  "영어영문학과",
  "예술체육대학",
  "융합바이오헬스전공",
  "융합응용화학과",
  "음악학과",
  "의사소통교실",
  "인공지능학과",
  "인문대학",
  "전자전기컴퓨터공학부",
  "정경대학",
  "조각학과",
  "조경학과",
  "중국어문화학과",
  "지능형반도체전공",
  "창업학",
  "철학과",
  "첨단인공지능전공",
  "컴퓨터과학부",
  "토목공학과",
  "통계학과",
  "평생교육학",
  "행정학과",
  "화학공학과",
  "환경공학부",
  "환경원예학과",
];

export const departmentMapping: Record<string, string> = {
  행정학과: "ADMINISTRATION",
  국제관계학과: "INTERNATIONAL_RELATIONS",
  경제학부: "ECONOMICS",
  사회복지학과: "SOCIAL_WELFARE",
  세무학과: "TAXATION",
  경영학부: "BUSINESS_MANAGEMENT",
  전자전기컴퓨터공학부: "ELECTRICAL_COMPUTER_ENGINEERING",
  화학공학과: "CHEMICAL_ENGINEERING",
  기계정보공학과: "MECHANICAL_INFORMATION_ENGINEERING",
  신소재공학과: "MATERIALS_SCIENCE_ENGINEERING",
  토목공학과: "CIVIL_ENGINEERING",
  컴퓨터과학부: "COMPUTER_SCIENCE",
  인공지능학과: "ARTIFICIAL_INTELLIGENCE",
  영어영문학과: "ENGLISH_LANGUAGE_LITERATURE",
  국어국문학과: "KOREAN_LANGUAGE_LITERATURE",
  국사학과: "KOREAN_HISTORY",
  철학과: "PHILOSOPHY",
  중국어문화학과: "CHINESE_CULTURE",
  수학과: "MATHEMATICS",
  통계학과: "STATISTICS",
  물리학과: "PHYSICS",
  생명과학과: "LIFE_SCIENCES",
  환경원예학과: "ENVIRONMENTAL_HORTICULTURE",
  융합응용화학과: "APPLIED_CHEMISTRY",
  "건축학부(건축공학)": "ARCHITECTURAL_ENGINEERING",
  "건축학부(건축학)": "ARCHITECTURE",
  도시공학과: "URBAN_ENGINEERING",
  교통공학과: "TRANSPORTATION_ENGINEERING",
  조경학과: "LANDSCAPE_ARCHITECTURE",
  도시행정학과: "URBAN_ADMINISTRATION",
  도시사회학과: "URBAN_SOCIOLOGY",
  공간정보공학과: "GEOINFORMATICS",
  환경공학부: "ENVIRONMENTAL_ENGINEERING",
  음악학과: "MUSIC",
  디자인학과: "DESIGN",
  환경조각학과: "ENVIRONMENTAL_SCULPTURE",
  스포츠과학과: "SPORTS_SCIENCE",
  자유전공학부: "LIBERAL_ARTS",
  융합전공학부: "INTERDISCIPLINARY_STUDIES",
  첨단융합학부: "ADVANCED_INTERDISCIPLINARY",
};

export const collegeMapping: Record<string, string> = {
  정경대학: "POLITICAL_ECONOMY",
  경영대학: "BUSINESS",
  공과대학: "ENGINEERING",
  인문대학: "HUMANITIES",
  자연과학대학: "NATURAL_SCIENCES",
  도시과학대학: "URBAN_SCIENCES",
  예술체육대학: "ARTS_PHYSICAL_EDUCATION",
  자유융합대학: "LIBERAL_INTERDISCIPLINARY",
};

export const departmentNoticeUrls: Record<DepartmentType, string> = {
  조경학과: "https://lauos.or.kr/notice",
  교통공학과:
    "https://www.uos.ac.kr/urbansciences/transport/korNotice/allList.do?list_id=urbansciences01&identified=anonymous&",
  "건축학부(건축학)": "https://uosarch.ac.kr/board/notice/",
};

export type DepartmentType = (typeof DEPARTMENT)[number];
export const reverseDepartmentMapping: Record<string, string> =
  Object.fromEntries(Object.entries(departmentMapping).map(([k, v]) => [v, k]));

// 단과대학별 학과 그룹화
export const COLLEGE_DEPARTMENT_MAP: Record<string, string[]> = {
  정경대학: [
    "행정학과",
    "국제관계학과",
    "경제학부",
    "사회복지학과",
    "세무학과",
  ],
  경영대학: ["경영학부"],
  공과대학: [
    "전자전기컴퓨터공학부",
    "화학공학과",
    "기계정보공학과",
    "신소재공학과",
    "토목공학과",
    "컴퓨터과학부",
    "인공지능학과",
  ],
  인문대학: [
    "영어영문학과",
    "국어국문학과",
    "국사학과",
    "철학과",
    "중국어문화학과",
  ],
  자연과학대학: [
    "수학과",
    "통계학과",
    "물리학과",
    "생명과학과",
    "환경원예학과",
    "융합응용화학과",
  ],
  도시과학대학: [
    "건축학전공",
    "건축공학전공",
    "도시공학과",
    "교통공학과",
    "조경학과",
    "도시행정학과",
    "도시사회학과",
    "공간정보공학과",
    "환경공학부",
  ],
  예술체육대학: [
    "음악학과",
    "산업디자인전공",
    "시각디자인전공",
    "조각학과",
    "스포츠과학과",
  ],
  자유융합대학: [
    "자유전공학부",
    "지능형반도체전공",
    "첨단인공지능전공",
    "융합바이오헬스전공",
    "빅데이터분석학전공",
  ],
  기타: [
    "교양교육부",
    "교양물리",
    "교양생물",
    "교양수학",
    "교양영어",
    "교양체육",
    "교양컴퓨터",
    "교양화학",
    "교직부",
    "국제교육원",
    "국제교류과",
    "국제도시개발학전공",
    "도시부동산기획경영학전공",
    "미디어콘텐츠학",
    "도시문화콘텐츠학",
    "동아시아문화학전공",
    "법규범제도학",
    "소방방재학과",
    "의사소통교실",
    "창업학",
    "평생교육학",
  ],
};
