name: auto-Assign Reviewer and Assignee

permissions:
  issues: write

on:
  pull_request:
    types: [opened, ready_for_review]
  issues:
    types: [opened]

jobs:
  pr-assign:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          assignees: ${{ github.actor }}
          reviewers: ${{ vars.REVIEWERS }}

  issue-assign:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - uses: gustavofreze/auto-assign@1.0.0
        with:
          assignees: ${{ github.actor }}
          github_token: ${{ secrets.GITHUB_TOKEN }}